blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns('',
                       url(r'^register/$', views.register, name='register'),
                       url(r'^login/$', views.login, name='login'),
                       url(r'^logout/$', views.logout, name='logout'),

                       url(r'^(\w+?)/home/$', views.home, name='home'),
                       url(r'^(\w+?)/blog/(?:(\d+)/)?$', views.blog, name='blog'),
                       url(r'^(\w+?)/view/(\d+)/$', views.view, name='view'),
                       url(r'^(\w+?)/edit/(?:(\d+)/)?$', views.edit, name='edit'),
                       url(r'^(\w+?)/archive/(\d{4}-\d{2})/(?:(\d+)/)?$', views.archive, name='archive'),
                       url(r'^(\w+?)/category/(\w+?)/(?:(\d+)/)?$', views.category, name='category'),
                       )

myblog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myblog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blog.urls',  namespace='blog')),
)

blog/models.py
from django.db import models
from myblog.settings import MEDIA_ROOT


class User(models.Model):
    username = models.CharField(max_length=100)  # 以后可以unique=True简化
    password = models.CharField(max_length=50)
    sex = models.CharField(max_length=10)
    head_show = models.FileField(upload_to=MEDIA_ROOT)
    register_date = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()

    def __str__(self):
        return self.username


class Tag(models.Model):
    tag_name = models.CharField(max_length=20)
    user = models.ForeignKey(User)


class BlogMonth(models.Model):
    month = models.DateTimeField()
    user = models.ForeignKey(User)


class Blog(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    content = models.TextField()
    month = models.ForeignKey(BlogMonth, null=True, blank=True)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, related_name='comment_author')
    target = models.ForeignKey(User, related_name='comment_target')
    created_time = models.DateTimeField()
    content = models.TextField()


class BlogImg(models.Model):
    image = models.FileField(upload_to=MEDIA_ROOT)
    blog = models.ForeignKey(Blog)


class Photo(models.Model):
    photo = models.FileField(upload_to=MEDIA_ROOT)
    author = models.ForeignKey(User)
    description = models.CharField(max_length=100)

blog/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email Address'}))


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username or Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))


class BlogForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
                            label='Title')
    content = forms.CharField(widget=forms.HiddenInput, label='Content')
    tag = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tags here'}),
                          required=False, help_text='multiple tags must separate by a comma', label='Tags',)
    delete = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

blog/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime
from blog.models import *
from blog.forms import *
import re


@csrf_exempt
def register(request):
    if request.method == 'POST':
        rf = RegisterForm(request.POST)
        if rf.is_valid():
            username = rf.cleaned_data['username']
            password = rf.cleaned_data['password']
            confirm_password = rf.cleaned_data['confirm_password']
            email = rf.cleaned_data['email']
            error = False
            error_message = []
            if User.objects.filter(username=username):
                error = True
                error_message.append('Username exists. ')
            if password != confirm_password:
                error = True
                error_message.append('Passwords not equal. ')
            if User.objects.filter(email=email):
                error = True
                error_message.append('Email exists.')
            if error:
                rf.cleaned_data['password'] = ''
                rf.cleaned_data['confirm_password'] = ''
                error_message = ''.join(error_message)
                return render_to_response('register.html', {'register_form': rf, 'error_message': error_message})
            User.objects.create(username=username, password=password, email=email)
            request.session['username'] = username
            return HttpResponse('ok')
    else:
        rf = RegisterForm()
        try:
            del request.session['username']
        except KeyError:
            pass
    return render_to_response('register.html', {'register_form': rf})


@csrf_exempt
def login(request):
    if request.method == 'POST':
        lf = LoginForm(request.POST)
        if lf.is_valid():
            username = lf.cleaned_data['username']
            password = lf.cleaned_data['password']
            user = User.objects.filter(username__exact=username, password__exact=password)
            if user:
                request.session['username'] = username
                return HttpResponseRedirect('/%s/home/' % username)
            user = User.objects.select_related().filter(email__exact=username, password__exact=password)
            if user:
                username = user[0].username
                request.session['username'] = username
                return HttpResponseRedirect('/%s/home/' % username)
            else:
                error_message = 'Username or Password incorrect'
                lf.cleaned_data['password'] = ''
                return render_to_response('login.html', {'login_form': lf, 'error_message': error_message})
    else:
        username = request.session.get('username', '')
        if not username or not User.objects.filter(username=username):
            lf = LoginForm()
            return render_to_response('login.html', {'login_form': lf})
        else:
            return HttpResponseRedirect('/%s/home/' % username)


def logout(request):
    try:
        del request.session['username']
    except KeyError:
        pass
    return HttpResponse('logout')


def blog(request, username, page=''):
    user = get_object_or_404(User, username=username)
    blog_list = list(user.blog_set.all().order_by('created_time').reverse())
    return pageinate(request, username, blog_list, page)


def archive(request, username, time, page=''):
    user = get_object_or_404(User, username=username)
    archive_time = datetime(int(time[:4]), int(time[5:]), 1)
    archive_month = get_object_or_404(BlogMonth, month=archive_time, user=user)
    blog_list = list(archive_month.blog_set.all().order_by('created_time').reverse())
    if not blog_list:
        return Http404
    archive_month = archive_month.month.strftime('%Y-%m')
    return pageinate(request, username, blog_list, page, archive_month)


def get_archive_dict_list(user):
    archive_list = list(user.blogmonth_set.all().order_by('month').reverse())
    archive_dict_list = []
    for month in archive_list:
        archive_dict_list.append({'month': month.month.strftime('%Y-%m'), 'num': month.blog_set.count()})
    return archive_dict_list


def category(request, username, tag, page=''):
    user = get_object_or_404(User, username=username)
    category_tag = get_object_or_404(Tag, tag_name=tag, user=user)
    blog_list = list(category_tag.blog_set.all())
    if not blog_list:
        return Http404
    return pageinate(request, username, blog_list, page, category_tag=category_tag.tag_name)


def get_category_dict_list(user):
    category_list = list(user.tag_set.all())
    category_dict_list = []
    for tag in category_list:
        if tag.blog_set.count():
            category_dict_list.append({'category_name': tag.tag_name, 'num': tag.blog_set.count()})
    return category_dict_list


def pageinate(request, username, blog_list, page, archive_month=None, category_tag=None):
    user = User.objects.get(username=username)
    if request.session.get('username', '') == username:
        user_self = True
    else:
        user_self = False
    try:
        page = int(page)
    except TypeError:
        page = 1
    pages = int((len(blog_list) + 10 - 1) / 10)
    if page > pages or page < 1:
        return HttpResponseRedirect('/%s/blog/' % username)
    try:
        uncategorized_tag = get_object_or_404(Tag, tag_name='Uncategorized', user=user)
    except ObjectDoesNotExist:
        uncategorized_tag = None
    context = {'blog_list': blog_list, 'username': username, 'user_self': user_self, 'pages': pages,
               'archive_dict_list': get_archive_dict_list(user), 'archive_month': archive_month,
               'category_dict_list': get_category_dict_list(user), 'category_tag': category_tag,
               'uncategorized_tag': uncategorized_tag}
    if pages > 1:
        context['blog_list'] = blog_list[(page-1)*10: page*10]
        context['page'] = page
        context['last_page'] = page - 1
        context['next_page'] = page + 1
        context['range'] = range(1, pages + 1)
    return render_to_response('blog.html', context)


def home(request, username):
    get_object_or_404(User, username=username)
    return render_to_response('home.html', {'username': username})


def view(request, username, pid):
    user = get_object_or_404(User, username=username)
    article = get_object_or_404(Blog, author=user, pk=pid)
    article_list = list(Blog.objects.order_by('created_time').reverse())
    index = article_list.index(article)
    if index > 0:
        next_article = article_list[index - 1]
    else:
        next_article = None
    if index < len(article_list) - 1:
        last_article = article_list[index + 1]
    else:
        last_article = None
    if request.session.get('username', '') == username:
        user_self = True
    else:
        user_self = False
    try:
        uncategorized_tag = get_object_or_404(Tag, tag_name='Uncategorized', user=user)
    except ObjectDoesNotExist:
        uncategorized_tag = None
    context = {'username': username, 'blog': article, 'user_self': user_self, 'next': next_article,
               'last': last_article, 'archive_dict_list': get_archive_dict_list(user),
               'category_dict_list': get_category_dict_list(user), 'uncategorized_tag': uncategorized_tag}
    return render_to_response('view.html', context)


@csrf_exempt
def edit(request, username, pid=''):
    if request.session.get('username', '') == username:
        user = User.objects.get(username=username)
        if request.method == 'POST':
            bf = BlogForm(request.POST)
            if bf.is_valid():
                if bf.cleaned_data['delete'] is True:
                    if pid:
                        Blog.objects.get(pk=pid).delete()
                    return HttpResponseRedirect('/%s/blog' % username)
                title = bf.cleaned_data['title']
                content = bf.cleaned_data['content']
                if not pid:
                    article = Blog.objects.create(author=user)
                    created_time = datetime.now()
                    created_time = datetime(created_time.year, created_time.month, 1)
                    blog_month = BlogMonth.objects.filter(month__exact=created_time, user__exact=user)
                    if not blog_month:
                        month = BlogMonth.objects.create(month=created_time, user=user)
                        article.month = month
                    else:
                        article.month = blog_month[0]
                else:
                    article = get_object_or_404(Blog, pk__exact=pid, author__exact=user)
                tag = re.sub(' ', '', bf.cleaned_data['tag']).split(',')
                tag_list = []
                for item in tag:
                    if item:
                        tag_list.append(item)
                article_tag_list = list(article.tag.all())
                prove_list = []
                if tag_list:
                    for item in tag_list:
                        try:
                            tag = Tag.objects.get(tag_name=item, user=user)
                            if tag not in article.tag.all():
                                article.tag.add(tag)
                            else:
                                prove_list.append(tag)
                        except ObjectDoesNotExist:
                            tag = Tag.objects.create(tag_name=item, user=user)
                            article.tag.add(tag)
                for tag in article_tag_list:
                    if tag not in prove_list:
                        article.tag.remove(tag)
                if not article.tag.count():
                    try:
                        tag = Tag.objects.get(tag_name='Uncategorized', user=user)
                    except ObjectDoesNotExist:

blog/templates/blog.html
{% extends 'base_blog.html' %}
{% load bootstrap3 %}

{% block title %} Blog {% endblock %}

{% block nav_blog %} class="active" {% endblock %}

{% block blog_list %}

  {% if user_self and not archive_month and not category_tag %}
    <div class="row">
        <div class="pull-right" style="padding-top: 43px;">
          <a href="{% url 'blog:edit' username %}" class="btn btn-primary" role="button">{% bootstrap_icon "plus" %} New blog</a>
        </div>
    </div>
  {% endif %}

  {% for blog in blog_list %}
    <div class="row">
      <div>
        <h2 class="page-header">
          <a href="{% url 'blog:view' username blog.pk%}">
            {{ blog.title }}
          </a>
        </h2>

        <div class="row" style="padding-top: 5px;padding-bottom: 10px">
          <div class="col-md-9">
            <div class="text-left">
              {% for tag in blog.tag.all %}
                {% if tag.tag_name %}
                  <a href="{% url 'blog:category' username tag.tag_name %}" class="btn btn-sm btn-default">{{ tag.tag_name }}</a>
                {% endif %}
              {% endfor %}
            </div>
          </div>

          <div class="col-md-3">
            <div class="text-right">
              <p class="text-muted"> {{ blog.created_time|date:"M. j, Y, H:i:s" }} </p>
            </div>
          </div>
        </div>

        {{ blog.content|safe|truncatewords_html:150 }}
      </div><br><br>

    </div>
  {% endfor %}

{% endblock %}

{% block pagination %}

  {% if pages > 1 %}
    <div class="row">
      <ul class="pagination pagination-lg pull-left">
        {% if page != 1 %}
          <li><a href="{% url 'blog:blog' username last_page %}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% for i in range %}
          {% if i == page %}
            <li class="active"><span>{{ i }}<span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="{% url 'blog:blog' username i %}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}

        {% if page != pages %}
          <li><a href="{% url 'blog:blog' username next_page %}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    </div>
  {% endif %}

{% endblock %}

blog/templates/edit.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %} Edit {% endblock %}

{% block link_or_script %}
  <link href="{% static 'bootstrap-wysiwyg/external/google-code-prettify/prettify.css' %}" rel="stylesheet">
  <link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
  <link href="{% static 'bootstrap-wysiwyg/index.css' %}" rel="stylesheet">
  <script src="{% static 'bootstrap-wysiwyg/external/jquery.hotkeys.js' %}"></script>
  <script src="{% static 'bootstrap-wysiwyg/external/google-code-prettify/prettify.js' %}"></script>
  <script src="{% static 'bootstrap-wysiwyg/bootstrap-wysiwyg.js' %}"></script>
{% endblock %}

{% block nav_blog %} class="active" {% endblock %}

{% block content %}
  <!-- a dialog of delete confirm -->
  <div class="modal fade" id="modal_confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
          </button>
          <h4 id="modal_header"></h4>
        </div>
        <div class="modal-body">
          <h4 id="modal_body" class="text-center"></h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">{% bootstrap_icon 'remove' %} Close</button>
          <button id="confirm_button" type="button" class="btn btn-primary">{% bootstrap_icon 'ok' %} Confirm</button>
        </div>
      </div>
    </div>
  </div>

  <br>
  <form id="blog_form" class="form" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label class="control-label" for="id_title">{{ blog_form.title.label }}</label>
      {{ blog_form.title }}
    </div>
    <div class="form-group">
      <label class="control-label" for="id_content">{{ blog_form.content.label }}</label>

      <!-- editor config -->
      <div class="hero-unit">
        <div id="alerts"></div>
        <div class="btn-toolbar" data-role="editor-toolbar" data-target="#editor">
          <div class="btn-group">
            <a class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" title="Font"><i class="icon-font"></i><b class="caret"></b></a>
            <ul class="dropdown-menu"></ul>
          </div>
          <div class="btn-group">
            <a class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="icon-text-height"></i>&nbsp;<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a data-edit="fontSize 5"><font size="5">Huge</font></a></li>
              <li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
              <li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
            </ul>
          </div>
          <div class="btn-group">
            <a class="btn btn-sm btn-default" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="icon-bold"></i></a>
            <a class="btn btn-sm btn-default" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="icon-italic"></i></a>
            <a class="btn btn-sm btn-default" data-edit="strikethrough" title="Strikethrough"><i class="icon-strikethrough"></i></a>
            <a class="btn btn-sm btn-default" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="icon-underline"></i></a>
          </div>
          <div class="btn-group">
            <a class="btn btn-sm btn-default" data-edit="insertunorderedlist" title="Bullet list"><i class="icon-list-ul"></i></a>
            <a class="btn btn-sm btn-default" data-edit="insertorderedlist" title="Number list"><i class="icon-list-ol"></i></a>
            <a class="btn btn-sm btn-default" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="icon-indent-left"></i></a>
            <a class="btn btn-sm btn-default" data-edit="indent" title="Indent (Tab)"><i class="icon-indent-right"></i></a>
          </div>
          <div class="btn-group">
            <a class="btn btn-sm btn-default" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="icon-align-left"></i></a>
            <a class="btn btn-sm btn-default" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="icon-align-center"></i></a>
            <a class="btn btn-sm btn-default" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="icon-align-right"></i></a>
            <a class="btn btn-sm btn-default" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="icon-align-justify"></i></a>
          </div>
          <div class="btn-group">
            <a class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="icon-link"></i></a>
            <div class="dropdown-menu input-append">
              <input class="span2" placeholder="URL" type="text" data-edit="createLink"/>
              <button class="btn btn-sm btn-default" type="button">Add</button>
            </div>
            <a class="btn btn-sm btn-default" data-edit="unlink" title="Remove Hyperlink"><i class="icon-cut"></i></a>
          </div>

          <div class="btn-group">
            <a class="btn btn-sm btn-default" title="Insert picture (or just drag & drop)" id="pictureBtn"><i class="icon-picture"></i></a>
            <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" />
          </div>
          <div class="btn-group">
            <a class="btn btn-sm btn-default" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="icon-undo"></i></a>
            <a class="btn btn-sm btn-default" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="icon-repeat"></i></a>
          </div>
          <input type="text" data-edit="inserttext" id="voiceBtn" x-webkit-speech="">
        </div>
        <div id="editor">
          {{ content|safe }}
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label" for="id_tag">{{ blog_form.tag.label }}</label>
      {{ blog_form.tag }}
      <span class="help-block">{{ blog_form.tag.help_text }}</span>
      {{ blog_form.delete }}
      {{ blog_form.content }}
    </div>
    {% buttons %}
      <div class="pull-right">
        <div class="btn-group">
          <button type="button" class="btn btn-primary" onclick="blog_submit();">{% bootstrap_icon "ok" %} Publish</button>
          {% if blog_id %}
            <button type="button" class="btn btn-primary" onclick="cancel_confirm();">{% bootstrap_icon "remove" %} Cancel</button>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal_confirm" onclick="delete_confirm();">{% bootstrap_icon "trash" %} Delete</button>
          {% else %}
            <button type="button" class="btn btn-primary" onclick="cancel_confirm();">{% bootstrap_icon "remove" %} Cancel</button>
          {% endif %}
        </div>
      </div>
    {% endbuttons %}
  </form>

{% endblock %}

{% block script %}
  <script type="text/javascript">
    function blog_del(){
      var form = document.getElementById('blog_form');
      form.delete.value = true;
      form.submit();
    }

    function blog_cancel() {
      {% if blog_id %}
        window.location.href = "{% url 'blog:view' username blog_id %}";
      {% else %}
        window.location.href = "{% url 'blog:blog' username %}";
      {% endif %}
    }

    function blog_submit(){
      var form=document.getElementById('blog_form');
      var editor = document.getElementById('editor');
      form.content.value = $('#editor').html();
      form.submit();
    }

    function cancel_confirm() {
      {% if not blog_id %}
        if (!$('#editor').cleanHtml()) {
          blog_cancel();
          return;
        }
      {% else %}
        if ($('#editor').html().trim() == document.getElementById('blog_form').content.value.trim()) {
          blog_cancel();
          return;
        }
      {% endif %}
      document.getElementById('modal_header').innerHTML = "Sure to Cancel?";
      document.getElementById('modal_body').innerHTML = "If you cancel, you will lose the updated content.";
      document.getElementById('confirm_button').onclick = blog_cancel;
      $('#modal_confirm').modal('toggle');
    }

    function delete_confirm() {
      document.getElementById('modal_header').innerHTML = "Sure to Delete?";
      document.getElementById('modal_body').innerHTML = "If you delete it, you will lose this post.";
      document.getElementById('confirm_button').onclick = blog_del;
    }
  </script>

  <!-- editor config script -->
  <script>
    $(function(){
      function initToolbarBootstrapBindings() {
        var fonts = ['Serif', 'Sans', 'Arial', 'Arial Black', 'Courier','Courier New', 'Comic Sans MS', 'Helvetica',
              'Impact', 'Lucida Grande', 'Lucida Sans', 'Tahoma', 'Times','Times New Roman', 'Verdana'],
            fontTarget = $('[title=Font]').siblings('.dropdown-menu');
        $.each(fonts, function (idx, fontName) {
          fontTarget.append($('<li><a data-edit="fontName ' + fontName +'" style="font-family:\''+ fontName +'\'">'+fontName + '</a></li>'));
        });
        $('a[title]').tooltip({container:'body'});
        $('.dropdown-menu input').click(function() {return false;})
            .change(function () {$(this).parent('.dropdown-menu').siblings('.dropdown-toggle').dropdown('toggle');})
            .keydown('esc', function () {this.value='';$(this).change();});

        $('[data-role=magic-overlay]').each(function () {
          var overlay = $(this), target = $(overlay.data('target'));
          overlay.css('opacity', 0).css('position', 'absolute').offset(target.offset()).width(target.outerWidth()).height(target.outerHeight());
        });
        if ("onwebkitspeechchange"  in document.createElement("input")) {
          var editorOffset = $('#editor').offset();
          $('#voiceBtn').css('position','absolute').offset({top: editorOffset.top, left: editorOffset.left+$('#editor').innerWidth()-35});
        } else {
          $('#voiceBtn').hide();
        }
	  };
	  function showErrorAlert (reason, detail) {
		  var msg='';
		  if (reason==='unsupported-file-type') { msg = "Unsupported format " +detail; }
		  else {
			  console.log("error uploading file", reason, detail);
		  }
		  $('<div class="alert"> <button type="button" class="close" data-dismiss="alert">&times;</button>'+
		  '<strong>File upload error</strong> '+msg+' </div>').prependTo('#alerts');
	  };
      initToolbarBootstrapBindings();
      $('#editor').wysiwyg({ fileUploadError: showErrorAlert} );
      window.prettyPrint && prettyPrint();
    });
  </script>

{% endblock %}

blog/templates/login.html
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>Login</title>
</head>
<body>
{% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form method="post">
  {% csrf_token %}
  <p>{{ login_form.username }}</p>
  <p>{{ login_form.password }}</p>
  <input type="submit" value="login">
</form>
</body>
</html>

blog/templates/view.html
{% extends 'base_blog.html' %}
{% load bootstrap3 %}

{% block title %} {{ blog.title }} {% endblock %}

{% block blog_list %}
<div>

  <h2 class="page-header">{{ blog.title }}</h2>

  <div class="row" style="padding-top: 5px;">
    <!-- categories -->
    <div class="col-md-9">
      <div class="text-left">
        {% for tag in blog.tag.all %}
          {% if tag.tag_name %}
            <a href="{% url 'blog:category' username tag.tag_name %}" class="btn btn-sm btn-default">{{ tag.tag_name }}</a>
          {% endif %}
        {% endfor %}
      </div>
    </div>
    <!-- created time -->
    <div class="col-md-3">
      <div class="text-right">
        <p class="text-muted"> {{ blog.created_time|date:"M. j, Y, H:i:s" }} </p>
      </div>
    </div>
  </div>

  {{ blog.content|safe }}

  <br>

  <div class="row"><br><br></div>

  <div class="row">
    <div class="pull-right">
      <div class="btn-group">
        <a href="{% url 'blog:blog' username %}" class="btn btn-primary" role="button">{% bootstrap_icon "chevron-left" %} Back</a>
        {% if user_self %}
          <a href="{% url 'blog:edit' username blog.pk %}" class="btn btn-primary" role="button">{% bootstrap_icon "edit" %} Edit</a>
        {% endif %}
      </div>
    </div>
  </div><br><br>

  <div class="row">
    {% if last %}
      <a class="pull-left" href="{% url 'blog:view' username last.pk %}">{% bootstrap_icon "chevron-left" %} {{ last.title }}</a>
    {% else %}
      <p class="text-muted pull-left">{% bootstrap_icon "chevron-left" %} 已是第一篇</p>
    {% endif %}
    {% if next %}
      <a class="pull-right" href="{% url "blog:view" username next.pk %}">{{ next.title }} {% bootstrap_icon "chevron-right" %}</a>
    {% else %}
      <p class="text-muted pull-right">已是最后一篇 {% bootstrap_icon "chevron-right" %}</p>
    {% endif %}
  </div>
</div>
{% endblock %}